version: 2.1
jobs:
  build:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run: cargo fmt -- --check
      - run: cargo install diesel_cli
      - run: diesel setup
      - run: cargo test
