version: 2.1
jobs:
  build:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run: rustup -V
      - run: cargo fmt -- --check
      - run: cargo test
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
